application:
  config:
    profile: dev_

info:
  component: financial-entity

server:
  servlet:
    context-path: "/financial-entity"
  port: 9137

spring:
  application:
    name: financial-entity
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://dev-consumption-usos.ch06w7as3fxd.us-east-1.rds.amazonaws.com:5432/posgres
    username: postgres
    password: MSDjy[8MyUOpi4{rzgs[
    driver-class-name: org.postgresql.Driver
    connection-test-query: "SELECT 1 FROM DUAL"
    test-while-idle: true
    test-on-borrow: true
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

endpoints:
  enabled: false

